version: "3.4"

services:
  api-service-dev:
    image: python:3.11-slim
    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
